catalog:
  '@shikijs/transformers': ^3.1.0
  '@shikijs/vitepress-twoslash': ^3.1.0
  '@vitest/coverage-v8': ^3.0.7
  svg-eslint-parser: ^0.0.2
  twoslash: ^0.3.1
  twoslash-eslint: ^0.3.1
  vitest: ^3.0.7
packages:
  - .
  - docs
