packages:
  - .
  - docs
catalog:
  '@shikijs/transformers': ^3.2.1
  '@shikijs/vitepress-twoslash': ^3.2.1
  '@vitest/coverage-v8': ^3.0.9
  svg-eslint-parser: ^0.0.2
  twoslash: ^0.3.1
  twoslash-eslint: ^0.3.1
  vitest: ^3.0.9
overrides:
  '@shikijs/core': ^3.1.0
  '@shikijs/markdown-it': ^3.1.0
  '@shikijs/rehype': ^3.1.0
  '@shikijs/transformers': ^3.1.0
  '@shikijs/types': ^3.1.0
  esbuild: ^0.25.0
  shiki: ^3.1.0
onlyBuiltDependencies:
  - esbuild
