packages:
  - .
  - docs
catalog:
  '@iconify-json/ri': ^1.2.5
  '@ntnyq/eslint-config': ^4.3.0
  '@ntnyq/prettier-config': ^3.0.1
  '@ntnyq/utils': ^0.7.2
  '@shikijs/transformers': ^3.6.0
  '@shikijs/vitepress-twoslash': ^3.6.0
  '@types/json-schema': ^7.0.15
  '@types/markdown-it-container': ^2.0.10
  '@types/node': ^22.15.32
  '@vitest/coverage-v8': ^3.2.3
  bumpp: ^10.1.1
  eslint: ^9.29.0
  eslint-plugin-eslint-plugin: ^6.4.0
  eslint-vitest-rule-tester: ^2.2.0
  husky: ^9.1.7
  markdown-it-container: ^4.0.0
  nano-staged: ^0.8.0
  npm-run-all2: ^8.0.4
  prettier: ^3.5.3
  svg-eslint-parser: ^0.0.4
  tinyglobby: ^0.2.14
  twoslash: ^0.3.1
  twoslash-eslint: ^0.3.1
  typescript: ^5.8.3
  unbuild: ^3.5.0
  uncase: ^0.1.0
  unocss: ^66.2.1
  unplugin-vue-components: ^28.7.0
  vite: ^6.3.5
  vitepress: ^2.0.0-alpha.6
  vitepress-plugin-group-icons: ^1.6.0
  vitest: ^3.2.3
  vue: ^3.5.16
overrides:
  esbuild: ^0.25.4
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
