catalog:
  '@shikijs/transformers': ^2.4.2
  '@shikijs/vitepress-twoslash': ^2.4.2
  '@vitest/coverage-v8': ^3.0.5
  svg-eslint-parser: ^0.0.2
  twoslash: ^0.2.12
  twoslash-eslint: ^0.2.12
  vitest: ^3.0.5
packages:
  - .
  - docs
