catalog:
  '@shikijs/transformers': ^3.0.0
  '@shikijs/vitepress-twoslash': ^3.0.0
  '@vitest/coverage-v8': ^3.0.6
  svg-eslint-parser: ^0.0.2
  twoslash: ^0.2.12
  twoslash-eslint: ^0.2.12
  vitest: ^3.0.6
packages:
  - .
  - docs
